### ISSUE TITLE
关于anjuke

### ISSUE THREAD

**Issue by xumeivs** [TRHX/Python3-Spider-Practice#2]
敢问一下博主，安居客识别爬虫的策略是什么? 换ip都不能逃过验证码。

**Comment by TRHX** [comment]
> 敢问一下博主，安居客识别爬虫的策略是什么? 换ip都不能逃过验证码。

说明使用的IP不干净，太多用户跑了，你拿到的IP已经被其他客户跑黑了，只能硬过验证码
